from setuptools import setup

setup(name='bcc-python',
      version="0.0.2",
      description='bcc-python',
      author="Neeky",
      author_email="neeky@live.com",
      maintainer='Neeky',
      maintainer_email='neeky@live.com',
      scripts=['bin/argdist','bin/bashreadline','bin/bindsnoop','bin/biolatency','bin/biolatpcts','bin/biopattern',
        'bin/biosnoop','bin/biotop','bin/bitesize','bin/bpflist','bin/btrfsdist','bin/btrfsslower','bin/cachestat',
        'bin/cachetop','bin/capable','bin/compactsnoop','bin/cpudist','bin/cpuunclaimed','bin/criticalstat',
        'bin/dbslower','bin/dbstat','bin/dcsnoop','bin/dcstat','bin/deadlock','bin/dirtop','bin/drsnoop',
        'bin/execsnoop','bin/exitsnoop','bin/ext4dist','bin/ext4slower','bin/filelife','bin/fileslower',
        'bin/filetop','bin/funccount','bin/funcinterval','bin/funclatency','bin/funcslower','bin/gethostlatency',
        'bin/hardirqs','bin/inject','bin/killsnoop','bin/klockstat','bin/kvmexit','bin/llcstat','bin/mdflush',
        'bin/memleak','bin/mountsnoop','bin/mysqld_qslower','bin/netqtop','bin/nfsdist','bin/nfsslower',
        'bin/offcputime','bin/offwaketime','bin/oomkill','bin/opensnoop','bin/pidpersec','bin/profile',
        'bin/readahead','bin/runqlat','bin/runqlen','bin/runqslower','bin/shmsnoop','bin/slabratetop',
        'bin/sofdsnoop','bin/softirqs','bin/solisten','bin/sslsniff','bin/stackcount','bin/statsnoop',
        'bin/swapin','bin/syncsnoop','bin/syscount','bin/tcpaccept','bin/tcpcong','bin/tcpconnect','bin/tcpconnlat',
        'bin/tcpdrop','bin/tcplife','bin/tcpretrans','bin/tcprtt','bin/tcpstates','bin/tcpsubnet','bin/tcpsynbl',
        'bin/tcptop','bin/tcptracer','bin/threadsnoop','bin/tplist','bin/trace','bin/ttysnoop','bin/vfscount',
        'bin/vfsstat','bin/virtiostat','bin/wakeuptime','bin/xfsdist','bin/xfsslower','bin/zfsdist',],
      packages=['bcc'],
      url='https://github.com/Neeky/bcc-python',
      python_requires='>=3.6.*',
      classifiers=[
          'Development Status :: 4 - Beta',
          'Intended Audience :: Developers',
          'Operating System :: POSIX',
          'Programming Language :: Python :: 3.6',
          'Programming Language :: Python :: 3.7',
          'Programming Language :: Python :: 3.8',
          'Programming Language :: Python :: 3.9',
          'Programming Language :: Python :: 3.10',
          'Programming Language :: Python :: 3.11']
      )